### ISSUE TITLE
build error (Node 7.7.0)

### ISSUE THREAD

**Issue by Nicolab** [atom-archive/marker-index#8]
Hello,

Build fails on Node 7.7.0 (Ubuntu 16.04 LTS)

```log
npm install -g slap@latest
/home/nico/.nvm/versions/node/v7.7.0/bin/slap -> /home/nico/.nvm/versions/node/v7.7.0/lib/node_modules/slap/slap.js

> marker-index@4.0.0 install /home/nico/.nvm/versions/node/v7.7.0/lib/node_modules/slap/node_modules/marker-index
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make : on entre dans le répertoire « /home/nico/.nvm/versions/node/v7.7.0/lib/node_modules/slap/node_modules/marker-index/build »
  CXX(target) Release/obj.target/marker_index/src/native/iterator.o
  CXX(target) Release/obj.target/marker_index/src/native/marker-index-wrapper.o
In file included from ../../nan/nan.h:47:0,
                 from ../src/native/marker-index-wrapper.cc:2:
/home/nico/.node-gyp/7.7.0/include/node/node.h:44:33: fatal error: tracing/trace_event.h: Aucun fichier ou dossier de ce type
compilation terminated.
marker_index.target.mk:102 : la recette pour la cible « Release/obj.target/marker_index/src/native/marker-index-wrapper.o » a échouée
make: *** [Release/obj.target/marker_index/src/native/marker-index-wrapper.o] Erreur 1
make : on quitte le répertoire « /home/nico/.nvm/versions/node/v7.7.0/lib/node_modules/slap/node_modules/marker-index/build »
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/nico/.nvm/versions/node/v7.7.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-64-generic
gyp ERR! command "/home/nico/.nvm/versions/node/v7.7.0/bin/node" "/home/nico/.nvm/versions/node/v7.7.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/nico/.nvm/versions/node/v7.7.0/lib/node_modules/slap/node_modules/marker-index
gyp ERR! node -v v7.7.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
/home/nico/.nvm/versions/node/v7.7.0/lib
└── (empty)

npm ERR! Linux 4.4.0-64-generic
npm ERR! argv "/home/nico/.nvm/versions/node/v7.7.0/bin/node" "/home/nico/.nvm/versions/node/v7.7.0/bin/npm" "install" "-g" "slap@latest"
npm ERR! node v7.7.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! marker-index@4.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the marker-index@4.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the marker-index package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs marker-index
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls marker-index
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/nico/npm-debug.log
```

**Comment by lee-dohm** [comment]
All repositories in the [atom-archive organization](https://github.com/atom-archive) are unmaintained and deprecated. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
